export type MenuItem = {
  id: number;
  name: string;
  description: string;
  price: number;
  category: "Hot Drinks" | "Cold Drinks" | "Pastries" | "Specials";
  image: string;
  totalOrders: number;
  isTopItem: boolean;
  calories: number;
  prepTime: number;
  tags: string[];
  sizes: { label: "S" | "M" | "L"; priceAdd: number }[];
};

export const menuItems: MenuItem[] = [
  {
    id: 1,
    name: "Signature Espresso",
    description: "Double shot of our house-blend single-origin beans, pulled at 9 bar.",
    price: 3.5,
    category: "Hot Drinks",
    image: "https://images.unsplash.com/photo-1632789397993-863a2f7f4267?w=400&h=300&fit=crop&auto=format",
    totalOrders: 1842,
    isTopItem: true,
    calories: 5,
    prepTime: 2,
    tags: ["Strong", "Classic"],
    sizes: [{ label: "S", priceAdd: 0 }, { label: "M", priceAdd: 0.5 }],
  },
  {
    id: 2,
    name: "Velvet Cappuccino",
    description: "Espresso with steamed microfoam milk, finished with a dusting of cacao.",
    price: 4.5,
    category: "Hot Drinks",
    image: "https://images.unsplash.com/photo-1534234757579-8ad69d218ad4?w=400&h=300&fit=crop&auto=format",
    totalOrders: 1204,
    isTopItem: false,
    calories: 120,
    prepTime: 4,
    tags: ["Creamy", "Classic"],
    sizes: [{ label: "S", priceAdd: 0 }, { label: "M", priceAdd: 0.5 }, { label: "L", priceAdd: 1 }],
  },
  {
    id: 3,
    name: "Caramel Cloud Latte",
    description: "Espresso with silky steamed milk and house-made salted caramel drizzle.",
    price: 5.5,
    category: "Hot Drinks",
    image: "https://images.unsplash.com/photo-1497636577773-f1231844b336?w=400&h=300&fit=crop&auto=format",
    totalOrders: 987,
    isTopItem: false,
    calories: 210,
    prepTime: 5,
    tags: ["Sweet", "Popular"],
    sizes: [{ label: "S", priceAdd: 0 }, { label: "M", priceAdd: 0.5 }, { label: "L", priceAdd: 1 }],
  },
  {
    id: 4,
    name: "Flat White",
    description: "Ristretto shots with velvety micro-steamed whole milk. Rich and intense.",
    price: 4.0,
    category: "Hot Drinks",
    image: "https://images.unsplash.com/photo-1503240778100-fd245e17a273?w=400&h=300&fit=crop&auto=format",
    totalOrders: 743,
    isTopItem: false,
    calories: 100,
    prepTime: 4,
    tags: ["Strong", "Smooth"],
    sizes: [{ label: "S", priceAdd: 0 }, { label: "M", priceAdd: 0.5 }],
  },
  {
    id: 5,
    name: "Cold Brew Reserve",
    description: "18-hour cold-steeped Guatemalan beans over ice. Smooth and chocolatey.",
    price: 5.0,
    category: "Cold Drinks",
    image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=400&h=300&fit=crop&auto=format",
    totalOrders: 1356,
    isTopItem: false,
    calories: 15,
    prepTime: 1,
    tags: ["Smooth", "Low-acid"],
    sizes: [{ label: "M", priceAdd: 0 }, { label: "L", priceAdd: 1 }],
  },
  {
    id: 6,
    name: "Iced Vanilla Latte",
    description: "Cold espresso, cold milk, Madagascar vanilla syrup, ice. Refreshing classic.",
    price: 5.5,
    category: "Cold Drinks",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop&auto=format",
    totalOrders: 918,
    isTopItem: false,
    calories: 190,
    prepTime: 3,
    tags: ["Sweet", "Refreshing"],
    sizes: [{ label: "M", priceAdd: 0 }, { label: "L", priceAdd: 1 }],
  },
  {
    id: 7,
    name: "Nitro Cold Brew",
    description: "Cold brew infused with nitrogen for a creamy, Guinness-like cascade.",
    price: 6.0,
    category: "Cold Drinks",
    image: "https://images.unsplash.com/photo-1558122104-355edad709f6?w=400&h=300&fit=crop&auto=format",
    totalOrders: 612,
    isTopItem: false,
    calories: 10,
    prepTime: 1,
    tags: ["Creamy", "Unique"],
    sizes: [{ label: "M", priceAdd: 0 }],
  },
  {
    id: 8,
    name: "Matcha Ceremonial Latte",
    description: "Ceremonial grade matcha whisked with steamed oat milk and honey.",
    price: 6.0,
    category: "Specials",
    image: "https://images.unsplash.com/photo-1559001724-fbad036dbc9e?w=400&h=300&fit=crop&auto=format",
    totalOrders: 534,
    isTopItem: false,
    calories: 150,
    prepTime: 5,
    tags: ["Earthy", "Antioxidant"],
    sizes: [{ label: "S", priceAdd: 0 }, { label: "M", priceAdd: 0.5 }, { label: "L", priceAdd: 1 }],
  },
  {
    id: 9,
    name: "Honey Lavender Cortado",
    description: "Equal parts ristretto and steamed milk with lavender honey syrup.",
    price: 5.0,
    category: "Specials",
    image: "https://images.unsplash.com/photo-1462917882517-e150004895fa?w=400&h=300&fit=crop&auto=format",
    totalOrders: 289,
    isTopItem: false,
    calories: 80,
    prepTime: 4,
    tags: ["Floral", "Seasonal"],
    sizes: [{ label: "S", priceAdd: 0 }],
  },
  {
    id: 10,
    name: "Butter Croissant",
    description: "Laminated dough, 72-hour ferment, all-butter. Flaky outside, tender inside.",
    price: 3.5,
    category: "Pastries",
    image: "https://images.unsplash.com/photo-1530610476181-d83430b64dcd?w=400&h=300&fit=crop&auto=format",
    totalOrders: 876,
    isTopItem: false,
    calories: 340,
    prepTime: 1,
    tags: ["Buttery", "Flaky"],
    sizes: [{ label: "M", priceAdd: 0 }],
  },
  {
    id: 11,
    name: "Blueberry Bran Muffin",
    description: "Baked fresh daily with wild blueberries and a lemon zest glaze.",
    price: 4.0,
    category: "Pastries",
    image: "https://images.unsplash.com/photo-1567752588693-ad10a647c5a3?w=400&h=300&fit=crop&auto=format",
    totalOrders: 431,
    isTopItem: false,
    calories: 290,
    prepTime: 1,
    tags: ["Fruity", "Wholesome"],
    sizes: [{ label: "M", priceAdd: 0 }],
  },
  {
    id: 12,
    name: "Cardamom Morning Bun",
    description: "Brioche dough rolled with brown butter, cinnamon, and cardamom sugar.",
    price: 4.5,
    category: "Pastries",
    image: "https://images.unsplash.com/photo-1643944471768-2d2eac3afb6d?w=400&h=300&fit=crop&auto=format",
    totalOrders: 198,
    isTopItem: false,
    calories: 380,
    prepTime: 1,
    tags: ["Spiced", "Seasonal"],
    sizes: [{ label: "M", priceAdd: 0 }],
  },
];

export const categories = ["All", "Hot Drinks", "Cold Drinks", "Specials", "Pastries"] as const;
export type Category = (typeof categories)[number];
